// ============================================================================
//  DỮ LIỆU NGUỒN CỦA DANH MỤC VẬT TƯ TIÊU HAO (sản phụ khoa).
//  Nguồn: tài liệu tham khảo "Danh mục vật tư tiêu hao người bệnh có thể phải
//  chi trả trong khám sản phụ khoa", phiên bản tháng 8/2026.
//  File này CHỈ dùng cho lệnh nạp danh mục (npm run seed:vat-tu). Sau khi nạp,
//  bảng vat_tu_tieu_hao trong database là nguồn duy nhất cho giao diện và báo cáo.
//
//  Danh mục không kèm đơn giá: giá thu do bệnh viện phê duyệt và cập nhật sau.
// ============================================================================

export type NhomVatTu = { id: number; ten: string; khoa: string[] };
export type VatTuMau = { stt: number; nhom: number; ten: string; ghi_chu: string };

export const NHOM_VAT_TU: NhomVatTu[] = [
  { id: 1, ten: "Khám và lấy mẫu phụ khoa", khoa: ["phu", "san"] },
  { id: 2, ten: "Xét nghiệm Pap smear và HPV", khoa: ["phu"] },
  { id: 3, ten: "Siêu âm sản phụ khoa", khoa: ["san", "phu", "ivf"] },
  { id: 4, ten: "Khám thai và theo dõi sản khoa", khoa: ["san"] },
  { id: 5, ten: "Soi cổ tử cung và sinh thiết", khoa: ["phu"] },
  { id: 6, ten: "Đặt vòng và cấy que tránh thai", khoa: ["phu"] },
  { id: 7, ten: "Tiêm truyền và điều trị ngoại trú", khoa: ["san", "phu", "ivf", "sosinh"] },
  { id: 8, ten: "Thủ thuật phụ khoa", khoa: ["phu"] },
  { id: 9, ten: "Sinh thường và chăm sóc sau sinh", khoa: ["san", "sosinh"] },
  { id: 10, ten: "Phẫu thuật sản phụ khoa", khoa: ["san", "phu"] },
  { id: 11, ten: "Hỗ trợ sinh sản và IVF", khoa: ["ivf"] },
  { id: 12, ten: "Tiện ích người bệnh tự nguyện", khoa: ["san", "phu", "ivf", "sosinh"] },
];

export const DANH_MUC_VAT_TU: VatTuMau[] = [
  // 1. Vật tư khám và lấy mẫu phụ khoa
  { stt: 1, nhom: 1, ten: "Mỏ vịt âm đạo nhựa dùng một lần", ghi_chu: "Khám âm đạo và cổ tử cung." },
  { stt: 2, nhom: 1, ten: "Gel bôi trơn y tế", ghi_chu: "Hỗ trợ khám phụ khoa, đặt mỏ vịt hoặc thực hiện thủ thuật." },
  { stt: 3, nhom: 1, ten: "Que bông vô khuẩn dài", ghi_chu: "Lấy dịch âm đạo hoặc dịch cổ tử cung." },
  { stt: 4, nhom: 1, ten: "Que lấy mẫu âm đạo", ghi_chu: "Xét nghiệm viêm âm đạo, vi sinh hoặc bệnh lây truyền qua đường tình dục." },
  { stt: 5, nhom: 1, ten: "Que lấy mẫu cổ tử cung", ghi_chu: "Xét nghiệm lậu, Chlamydia, vi sinh hoặc kỹ thuật chuyên môn khác." },
  { stt: 6, nhom: 1, ten: "Ống hoặc môi trường vận chuyển mẫu", ghi_chu: "Bảo quản và vận chuyển bệnh phẩm đến phòng xét nghiệm." },
  { stt: 7, nhom: 1, ten: "Lam kính và lá kính", ghi_chu: "Soi tươi, nhuộm vi sinh hoặc làm tiêu bản tế bào." },
  { stt: 8, nhom: 1, ten: "Giấy thử pH âm đạo", ghi_chu: "Hỗ trợ đánh giá môi trường âm đạo." },
  { stt: 9, nhom: 1, ten: "Cốc đựng nước tiểu", ghi_chu: "Lấy mẫu xét nghiệm nước tiểu." },
  { stt: 10, nhom: 1, ten: "Que thử thai", ghi_chu: "Chẩn đoán thai sớm theo chỉ định hoặc theo yêu cầu." },
  { stt: 11, nhom: 1, ten: "Que thử nước tiểu nhiều thông số", ghi_chu: "Sàng lọc protein, glucose, bạch cầu và các thông số khác." },
  { stt: 12, nhom: 1, ten: "Bộ xét nghiệm viêm âm đạo nhanh", ghi_chu: "Phát hiện Candida, Trichomonas hoặc viêm âm đạo do vi khuẩn." },
  { stt: 13, nhom: 1, ten: "Bộ xét nghiệm bệnh lây truyền qua đường tình dục nhanh", ghi_chu: "Áp dụng khi có chỉ định hoặc người bệnh lựa chọn dịch vụ." },
  { stt: 14, nhom: 1, ten: "Lọ đựng bệnh phẩm", ghi_chu: "Nuôi cấy, xét nghiệm vi sinh hoặc lưu mẫu." },

  // 2. Vật tư xét nghiệm Pap smear và HPV
  { stt: 15, nhom: 2, ten: "Chổi Cervex-Brush", ghi_chu: "Lấy tế bào vùng chuyển tiếp cổ tử cung." },
  { stt: 16, nhom: 2, ten: "Chổi lấy tế bào cổ trong", ghi_chu: "Lấy mẫu kênh cổ tử cung." },
  { stt: 17, nhom: 2, ten: "Que Ayre", ghi_chu: "Pap smear truyền thống." },
  { stt: 18, nhom: 2, ten: "Bộ lấy mẫu Pap smear", ghi_chu: "Tầm soát ung thư cổ tử cung." },
  { stt: 19, nhom: 2, ten: "Lọ bảo quản tế bào nhúng dịch", ghi_chu: "ThinPrep hoặc kỹ thuật tế bào học nhúng dịch tương đương." },
  { stt: 20, nhom: 2, ten: "Que lấy mẫu HPV", ghi_chu: "Lấy mẫu xét nghiệm HPV." },
  { stt: 21, nhom: 2, ten: "Lọ bảo quản mẫu HPV", ghi_chu: "Bảo quản và vận chuyển mẫu HPV." },
  { stt: 22, nhom: 2, ten: "Lam kính đầu mờ", ghi_chu: "Làm tiêu bản Pap smear truyền thống." },
  { stt: 23, nhom: 2, ten: "Dung dịch cố định tế bào", ghi_chu: "Cố định tiêu bản." },
  { stt: 24, nhom: 2, ten: "Nhãn mã vạch bệnh phẩm", ghi_chu: "Nhận diện và truy xuất mẫu xét nghiệm." },

  // 3. Vật tư siêu âm sản phụ khoa
  { stt: 25, nhom: 3, ten: "Bao đầu dò âm đạo", ghi_chu: "Siêu âm đầu dò âm đạo." },
  { stt: 26, nhom: 3, ten: "Bao đầu dò vô khuẩn", ghi_chu: "Thủ thuật xâm lấn dưới hướng dẫn siêu âm." },
  { stt: 27, nhom: 3, ten: "Gel siêu âm thông thường", ghi_chu: "Siêu âm qua thành bụng." },
  { stt: 28, nhom: 3, ten: "Gel siêu âm vô khuẩn", ghi_chu: "Thủ thuật xâm lấn hoặc trường hợp yêu cầu vô khuẩn." },
  { stt: 29, nhom: 3, ten: "Tấm lót bàn siêu âm dùng một lần", ghi_chu: "Giữ vệ sinh và hạn chế nhiễm bẩn." },
  { stt: 30, nhom: 3, ten: "Giấy in ảnh siêu âm", ghi_chu: "Khi cung cấp ảnh in theo gói dịch vụ hoặc yêu cầu của người bệnh." },
  { stt: 31, nhom: 3, ten: "USB hoặc phương tiện lưu dữ liệu", ghi_chu: "Khi người bệnh yêu cầu nhận hình ảnh hoặc video siêu âm." },

  // 4. Vật tư khám thai và theo dõi sản khoa
  { stt: 32, nhom: 4, ten: "Que thử protein niệu", ghi_chu: "Sàng lọc hoặc theo dõi nguy cơ tiền sản giật." },
  { stt: 33, nhom: 4, ten: "Que thử glucose niệu", ghi_chu: "Theo dõi chuyển hóa glucose." },
  { stt: 34, nhom: 4, ten: "Bộ xét nghiệm rò ối", ghi_chu: "Sử dụng khi nghi ngờ vỡ ối hoặc rỉ ối." },
  { stt: 35, nhom: 4, ten: "Giấy thử pH dịch âm đạo", ghi_chu: "Hỗ trợ đánh giá tình trạng rò ối." },
  { stt: 36, nhom: 4, ten: "Điện cực theo dõi dùng một lần", ghi_chu: "Theo dõi điện tim hoặc thông số sinh tồn khi cần." },
  { stt: 37, nhom: 4, ten: "Dây đai monitoring sản khoa dùng riêng", ghi_chu: "Áp dụng nếu cơ sở cung cấp theo hình thức cá nhân hoặc dịch vụ." },
  { stt: 38, nhom: 4, ten: "Tấm lót thấm dịch", ghi_chu: "Khám thai, theo dõi chuyển dạ hoặc sau thủ thuật." },
  { stt: 39, nhom: 4, ten: "Băng vệ sinh sản phụ", ghi_chu: "Dùng khi ra máu, ra dịch hoặc sau thủ thuật." },
  { stt: 40, nhom: 4, ten: "Quần lót giấy", ghi_chu: "Khám, thủ thuật hoặc theo dõi chuyển dạ." },
  { stt: 41, nhom: 4, ten: "Bỉm người lớn", ghi_chu: "Theo dõi chuyển dạ, sau sinh hoặc sau phẫu thuật." },
  { stt: 42, nhom: 4, ten: "Túi nôn dùng một lần", ghi_chu: "Thai nghén, truyền dịch hoặc cấp cứu." },
  { stt: 43, nhom: 4, ten: "Cốc lấy mẫu xét nghiệm", ghi_chu: "Lấy nước tiểu hoặc bệnh phẩm khác." },

  // 5. Vật tư soi cổ tử cung và sinh thiết
  { stt: 44, nhom: 5, ten: "Chổi hoặc que lấy mẫu cổ tử cung", ghi_chu: "Lấy mẫu tế bào hoặc vi sinh bổ sung." },
  { stt: 45, nhom: 5, ten: "Kìm sinh thiết dùng một lần", ghi_chu: "Sinh thiết tổn thương cổ tử cung." },
  { stt: 46, nhom: 5, ten: "Curette nạo kênh cổ tử cung dùng một lần", ghi_chu: "Nạo kênh cổ tử cung theo chỉ định." },
  { stt: 47, nhom: 5, ten: "Săng vô khuẩn có lỗ", ghi_chu: "Thiết lập trường thủ thuật vô khuẩn." },
  { stt: 48, nhom: 5, ten: "Bơm tiêm và kim gây tê", ghi_chu: "Gây tê tại chỗ." },
  { stt: 49, nhom: 5, ten: "Thuốc hoặc vật liệu cầm máu", ghi_chu: "Kiểm soát chảy máu sau sinh thiết." },
  { stt: 50, nhom: 5, ten: "Gạc cầm máu chuyên dụng", ghi_chu: "Cầm máu và bảo vệ vị trí sinh thiết." },
  { stt: 51, nhom: 5, ten: "Lọ formalin bệnh phẩm", ghi_chu: "Bảo quản mô gửi giải phẫu bệnh." },
  { stt: 52, nhom: 5, ten: "Hộp hoặc túi vận chuyển bệnh phẩm", ghi_chu: "Vận chuyển mẫu mô an toàn." },
  { stt: 53, nhom: 5, ten: "Băng vệ sinh", ghi_chu: "Sử dụng sau thủ thuật." },

  // 6. Vật tư đặt vòng và cấy que tránh thai
  { stt: 54, nhom: 6, ten: "Vòng tránh thai chứa đồng", ghi_chu: "Thanh toán theo loại vòng và chính sách của cơ sở." },
  { stt: 55, nhom: 6, ten: "Dụng cụ tử cung chứa nội tiết", ghi_chu: "Chi phí thường khác vòng đồng và thường thuộc dịch vụ theo yêu cầu." },
  { stt: 56, nhom: 6, ten: "Bộ đặt vòng dùng một lần", ghi_chu: "Sử dụng khi không đi kèm sản phẩm." },
  { stt: 57, nhom: 6, ten: "Que cấy tránh thai", ghi_chu: "Thanh toán theo số que, loại sản phẩm và chương trình hỗ trợ nếu có." },
  { stt: 58, nhom: 6, ten: "Bộ dụng cụ cấy que", ghi_chu: "Phục vụ thủ thuật đặt que." },
  { stt: 59, nhom: 6, ten: "Bộ dụng cụ tháo que", ghi_chu: "Phục vụ thủ thuật tháo que." },
  { stt: 60, nhom: 6, ten: "Thuốc gây tê tại chỗ", ghi_chu: "Gây tê khi cấy hoặc tháo que." },
  { stt: 61, nhom: 6, ten: "Bơm tiêm và kim tiêm", ghi_chu: "Tiêm thuốc gây tê." },
  { stt: 62, nhom: 6, ten: "Dao rạch da dùng một lần", ghi_chu: "Tháo que hoặc xử trí tại vị trí cấy." },
  { stt: 63, nhom: 6, ten: "Miếng dán vết thương", ghi_chu: "Chăm sóc sau thủ thuật." },
  { stt: 64, nhom: 6, ten: "Băng ép", ghi_chu: "Giảm chảy máu và tụ máu." },
  { stt: 65, nhom: 6, ten: "Chỉ khâu", ghi_chu: "Dùng khi cần đóng vết rạch." },

  // 7. Vật tư tiêm truyền và điều trị ngoại trú
  { stt: 66, nhom: 7, ten: "Bơm tiêm các cỡ", ghi_chu: "Tiêm thuốc hoặc bơm rửa theo chỉ định." },
  { stt: 67, nhom: 7, ten: "Kim tiêm", ghi_chu: "Tiêm dưới da, tiêm bắp hoặc tiêm tĩnh mạch." },
  { stt: 68, nhom: 7, ten: "Kim luồn tĩnh mạch", ghi_chu: "Truyền dịch, dùng thuốc hoặc cấp cứu." },
  { stt: 69, nhom: 7, ten: "Dây truyền dịch", ghi_chu: "Truyền dịch và thuốc." },
  { stt: 70, nhom: 7, ten: "Dây nối tĩnh mạch", ghi_chu: "Kéo dài hoặc kết nối đường truyền." },
  { stt: 71, nhom: 7, ten: "Khóa ba chạc", ghi_chu: "Kết nối nhiều nhánh trên đường truyền." },
  { stt: 72, nhom: 7, ten: "Nút chặn kim luồn", ghi_chu: "Bảo vệ đường truyền tĩnh mạch." },
  { stt: 73, nhom: 7, ten: "Miếng dán cố định kim luồn", ghi_chu: "Cố định đường truyền." },
  { stt: 74, nhom: 7, ten: "Băng dính y tế", ghi_chu: "Cố định gạc và vật tư." },
  { stt: 75, nhom: 7, ten: "Bông cồn hoặc miếng sát khuẩn", ghi_chu: "Sát khuẩn vị trí tiêm hoặc lấy máu." },
  { stt: 76, nhom: 7, ten: "Gạc ép", ghi_chu: "Cầm máu sau tiêm hoặc lấy máu." },
  { stt: 77, nhom: 7, ten: "Kim lấy máu chân không", ghi_chu: "Lấy mẫu xét nghiệm." },
  { stt: 78, nhom: 7, ten: "Kim cánh bướm", ghi_chu: "Lấy máu hoặc truyền tĩnh mạch." },
  { stt: 79, nhom: 7, ten: "Ống nghiệm các loại", ghi_chu: "Lưu mẫu máu theo yêu cầu xét nghiệm." },

  // 8. Vật tư thực hiện thủ thuật phụ khoa
  { stt: 80, nhom: 8, ten: "Dao mổ hoặc lưỡi dao mổ dùng một lần", ghi_chu: "Rạch, dẫn lưu hoặc tiểu phẫu." },
  { stt: 81, nhom: 8, ten: "Chỉ khâu tự tiêu", ghi_chu: "Khâu niêm mạc hoặc mô mềm." },
  { stt: 82, nhom: 8, ten: "Chỉ khâu không tiêu", ghi_chu: "Khâu da hoặc trường hợp chuyên môn phù hợp." },
  { stt: 83, nhom: 8, ten: "Săng vô khuẩn", ghi_chu: "Thiết lập trường thủ thuật." },
  { stt: 84, nhom: 8, ten: "Gạc phẫu thuật có cản quang", ghi_chu: "Thủ thuật xâm lấn." },
  { stt: 85, nhom: 8, ten: "Vật liệu cầm máu", ghi_chu: "Kiểm soát chảy máu." },
  { stt: 86, nhom: 8, ten: "Băng hoặc miếng dán vết thương", ghi_chu: "Chăm sóc sau thủ thuật." },
  { stt: 87, nhom: 8, ten: "Dây hút dịch", ghi_chu: "Hút máu hoặc dịch." },
  { stt: 88, nhom: 8, ten: "Túi hoặc bình chứa dịch hút", ghi_chu: "Thu gom dịch." },
  { stt: 89, nhom: 8, ten: "Ống thông tiểu Foley", ghi_chu: "Dẫn lưu bàng quang liên tục." },
  { stt: 90, nhom: 8, ten: "Ống thông Nelaton", ghi_chu: "Thông tiểu ngắt quãng." },
  { stt: 91, nhom: 8, ten: "Túi đựng nước tiểu", ghi_chu: "Thu gom nước tiểu." },
  { stt: 92, nhom: 8, ten: "Gel bôi trơn vô khuẩn", ghi_chu: "Đặt ống thông hoặc dụng cụ." },
  { stt: 93, nhom: 8, ten: "Lọ đựng bệnh phẩm giải phẫu bệnh", ghi_chu: "Bảo quản mô bệnh phẩm." },
  { stt: 94, nhom: 8, ten: "Bộ nong cổ tử cung dùng một lần", ghi_chu: "Nong cổ tử cung theo chỉ định." },
  { stt: 95, nhom: 8, ten: "Ống hoặc canuyn hút buồng tử cung", ghi_chu: "Hút dịch, mô hoặc bệnh phẩm." },
  { stt: 96, nhom: 8, ten: "Bộ sinh thiết nội mạc tử cung Pipelle", ghi_chu: "Sinh thiết nội mạc tử cung." },
  { stt: 97, nhom: 8, ten: "Catheter bơm thuốc hoặc bơm buồng tử cung", ghi_chu: "Thực hiện kỹ thuật chuyên môn được chỉ định." },

  // 9. Vật tư trong sinh thường và chăm sóc sau sinh
  { stt: 98, nhom: 9, ten: "Băng vệ sinh sản phụ", ghi_chu: "Dùng sau sinh." },
  { stt: 99, nhom: 9, ten: "Bỉm người lớn", ghi_chu: "Dùng trong chuyển dạ hoặc sau sinh." },
  { stt: 100, nhom: 9, ten: "Quần lót giấy", ghi_chu: "Dùng trong thời gian nằm viện." },
  { stt: 101, nhom: 9, ten: "Tấm lót thấm dịch", ghi_chu: "Giường sinh, giường hậu sản hoặc chăm sóc sau sinh." },
  { stt: 102, nhom: 9, ten: "Bộ quần áo sơ sinh dùng một lần hoặc bộ sơ sinh dịch vụ", ghi_chu: "Theo gói sinh hoặc lựa chọn của gia đình." },
  { stt: 103, nhom: 9, ten: "Bỉm sơ sinh", ghi_chu: "Chăm sóc trẻ sơ sinh." },
  { stt: 104, nhom: 9, ten: "Khăn quấn trẻ", ghi_chu: "Theo gói dịch vụ hoặc nhu cầu gia đình." },
  { stt: 105, nhom: 9, ten: "Kẹp rốn dùng một lần", ghi_chu: "Kẹp dây rốn sau sinh." },
  { stt: 106, nhom: 9, ten: "Vòng định danh mẹ và bé", ghi_chu: "Nhận diện an toàn mẹ - con." },
  { stt: 107, nhom: 9, ten: "Bộ chăm sóc rốn", ghi_chu: "Chăm sóc rốn trẻ sơ sinh." },
  { stt: 108, nhom: 9, ten: "Chỉ khâu tầng sinh môn", ghi_chu: "Khâu phục hồi tầng sinh môn." },
  { stt: 109, nhom: 9, ten: "Lưỡi dao dùng trong thủ thuật sản khoa", ghi_chu: "Sử dụng theo chỉ định chuyên môn." },
  { stt: 110, nhom: 9, ten: "Ống thông tiểu và túi nước tiểu", ghi_chu: "Theo dõi trong chuyển dạ hoặc sau sinh." },
  { stt: 111, nhom: 9, ten: "Vật tư giảm đau ngoài màng cứng", ghi_chu: "Khi người bệnh đăng ký hoặc có chỉ định." },
  { stt: 112, nhom: 9, ten: "Bộ lấy và lưu trữ máu cuống rốn", ghi_chu: "Dịch vụ riêng do người bệnh lựa chọn." },

  // 10. Vật tư trong phẫu thuật sản phụ khoa
  { stt: 113, nhom: 10, ten: "Kim luồn, dây truyền và dây nối", ghi_chu: "Thiết lập đường truyền và gây mê hồi sức." },
  { stt: 114, nhom: 10, ten: "Ống thông tiểu và túi nước tiểu", ghi_chu: "Theo dõi bài niệu trong và sau phẫu thuật." },
  { stt: 115, nhom: 10, ten: "Chỉ khâu phẫu thuật", ghi_chu: "Đóng vết mổ và phục hồi tổ chức." },
  { stt: 116, nhom: 10, ten: "Lưỡi dao mổ", ghi_chu: "Thực hiện phẫu thuật." },
  { stt: 117, nhom: 10, ten: "Điện cực dao điện và tấm điện cực trung tính", ghi_chu: "Cắt, đốt và cầm máu." },
  { stt: 118, nhom: 10, ten: "Dây hút và túi chứa dịch", ghi_chu: "Hút và thu gom dịch." },
  { stt: 119, nhom: 10, ten: "Ống dẫn lưu và túi dẫn lưu", ghi_chu: "Dẫn lưu sau phẫu thuật." },
  { stt: 120, nhom: 10, ten: "Trocar nội soi dùng một lần", ghi_chu: "Phẫu thuật nội soi." },
  { stt: 121, nhom: 10, ten: "Dao hoặc kéo siêu âm dùng một lần", ghi_chu: "Cắt và hàn mô." },
  { stt: 122, nhom: 10, ten: "Kẹp hàn mạch dùng một lần", ghi_chu: "Cầm máu và đóng mạch." },
  { stt: 123, nhom: 10, ten: "Túi lấy bệnh phẩm nội soi", ghi_chu: "Lấy mô hoặc khối bệnh phẩm ra ngoài." },
  { stt: 124, nhom: 10, ten: "Kim khâu nội soi", ghi_chu: "Khâu phục hồi trong phẫu thuật nội soi." },
  { stt: 125, nhom: 10, ten: "Bộ dây bơm rửa nội soi", ghi_chu: "Bơm và hút dịch trong phẫu thuật." },
  { stt: 126, nhom: 10, ten: "Dụng cụ cắt hoặc lấy mô dùng một lần", ghi_chu: "Theo kỹ thuật và chỉ định phẫu thuật." },
  { stt: 127, nhom: 10, ten: "Lưới điều trị sa sinh dục", ghi_chu: "Phẫu thuật phục hồi sàn chậu khi có chỉ định." },
  { stt: 128, nhom: 10, ten: "Băng nâng niệu đạo", ghi_chu: "Điều trị tiểu không tự chủ." },
  { stt: 129, nhom: 10, ten: "Vật liệu chống dính", ghi_chu: "Giảm nguy cơ dính sau mổ." },
  { stt: 130, nhom: 10, ten: "Vật liệu cầm máu sinh học", ghi_chu: "Kiểm soát chảy máu tại chỗ." },
  { stt: 131, nhom: 10, ten: "Stapler hoặc ghim khâu phẫu thuật", ghi_chu: "Đóng mô theo kỹ thuật." },
  { stt: 132, nhom: 10, ten: "Bộ hút áp lực âm vết mổ", ghi_chu: "Chăm sóc vết mổ nguy cơ cao." },
  { stt: 133, nhom: 10, ten: "Miếng dán vết mổ chuyên dụng", ghi_chu: "Bảo vệ vết mổ." },
  { stt: 134, nhom: 10, ten: "Bóng chèn tử cung", ghi_chu: "Kiểm soát băng huyết sau sinh khi có chỉ định." },

  // 11. Vật tư hỗ trợ sinh sản và IVF
  { stt: 135, nhom: 11, ten: "Kim chọc hút noãn", ghi_chu: "Chọc hút noãn dưới hướng dẫn siêu âm." },
  { stt: 136, nhom: 11, ten: "Dây hút noãn", ghi_chu: "Kết nối kim chọc hút với hệ thống thu noãn." },
  { stt: 137, nhom: 11, ten: "Ống nghiệm dịch nang", ghi_chu: "Thu nhận dịch nang và noãn." },
  { stt: 138, nhom: 11, ten: "Đĩa Petri IVF và đĩa nuôi cấy phôi", ghi_chu: "Thao tác giao tử và nuôi phôi." },
  { stt: 139, nhom: 11, ten: "Môi trường lọc rửa tinh trùng", ghi_chu: "Chuẩn bị mẫu tinh trùng." },
  { stt: 140, nhom: 11, ten: "Môi trường thụ tinh và nuôi phôi", ghi_chu: "Thụ tinh và nuôi cấy phôi." },
  { stt: 141, nhom: 11, ten: "Dầu phủ môi trường", ghi_chu: "Duy trì điều kiện nuôi cấy." },
  { stt: 142, nhom: 11, ten: "Pipette giữ noãn, pipette ICSI và pipette hỗ trợ thoát màng", ghi_chu: "Vi thao tác trong labo IVF." },
  { stt: 143, nhom: 11, ten: "Catheter bơm tinh trùng", ghi_chu: "Bơm tinh trùng vào buồng tử cung." },
  { stt: 144, nhom: 11, ten: "Catheter chuyển phôi", ghi_chu: "Chuyển phôi vào buồng tử cung." },
  { stt: 145, nhom: 11, ten: "Catheter thử chuyển phôi", ghi_chu: "Đánh giá đường chuyển phôi." },
  { stt: 146, nhom: 11, ten: "Bộ lọc tinh trùng", ghi_chu: "Lọc rửa và chọn lọc tinh trùng." },
  { stt: 147, nhom: 11, ten: "Ống trữ tinh trùng", ghi_chu: "Bảo quản lạnh tinh trùng." },
  { stt: 148, nhom: 11, ten: "Cryotop hoặc dụng cụ thủy tinh hóa", ghi_chu: "Đông lạnh noãn hoặc phôi." },
  { stt: 149, nhom: 11, ten: "Môi trường đông và rã phôi", ghi_chu: "Bảo quản và phục hồi phôi/noãn đông lạnh." },
  { stt: 150, nhom: 11, ten: "Nhãn nhận diện chuyên dụng", ghi_chu: "Nhận diện, truy xuất và an toàn mẫu." },
  { stt: 151, nhom: 11, ten: "Bộ sinh thiết phôi", ghi_chu: "Lấy tế bào phục vụ xét nghiệm di truyền." },
  { stt: 152, nhom: 11, ten: "Kit xét nghiệm di truyền phôi", ghi_chu: "Thực hiện khi có chỉ định và dịch vụ được lựa chọn." },
  { stt: 153, nhom: 11, ten: "Bao đầu dò và gel siêu âm vô khuẩn", ghi_chu: "Chọc hút noãn hoặc chuyển phôi." },
  { stt: 154, nhom: 11, ten: "Bộ vật tư gây mê hoặc giảm đau", ghi_chu: "Chọc hút noãn và các thủ thuật liên quan." },

  // 12. Vật tư tiện ích người bệnh tự nguyện sử dụng
  { stt: 155, nhom: 12, ten: "Băng vệ sinh hoặc bỉm cao cấp", ghi_chu: "Sản phẩm tiện ích theo lựa chọn." },
  { stt: 156, nhom: 12, ten: "Quần lót giấy", ghi_chu: "Dùng trong khám, điều trị hoặc lưu viện." },
  { stt: 157, nhom: 12, ten: "Bộ đồ dùng cá nhân", ghi_chu: "Theo gói dịch vụ." },
  { stt: 158, nhom: 12, ten: "Bộ vệ sinh mẹ sau sinh", ghi_chu: "Dịch vụ tiện ích." },
  { stt: 159, nhom: 12, ten: "Bộ chăm sóc trẻ sơ sinh", ghi_chu: "Theo nhu cầu gia đình." },
  { stt: 160, nhom: 12, ten: "Khăn ướt, khăn khô và sản phẩm vệ sinh", ghi_chu: "Tiện ích cá nhân." },
  { stt: 161, nhom: 12, ten: "Bình sữa và dụng cụ cho trẻ", ghi_chu: "Theo lựa chọn của gia đình." },
  { stt: 162, nhom: 12, ten: "Vật tư phòng dịch vụ theo yêu cầu", ghi_chu: "Theo gói phòng hoặc dịch vụ." },
  { stt: 163, nhom: 12, ten: "USB lưu hình ảnh siêu âm", ghi_chu: "Cung cấp dữ liệu theo yêu cầu." },
  { stt: 164, nhom: 12, ten: "In thêm ảnh siêu âm", ghi_chu: "Ngoài số lượng ảnh được cấu thành trong gói." },
  { stt: 165, nhom: 12, ten: "Bộ xét nghiệm hoặc sàng lọc theo yêu cầu", ghi_chu: "Không có chỉ định hoặc ngoài phạm vi quyền lợi thanh toán." },
];

