// ============================================================================
//  DANH MUC BENH LY SAN PHU KHOA -- 80 benh, 8 nhom chuyen mon.
//  Nguon: tai lieu "Danh muc 80 benh ly san phu khoa" do benh vien cung cap.
//  Tai lieu KHONG kem ma ICD nen o "Ma ICD" van do nguoi dung tu nhap.
// ============================================================================

export const NHOM_BENH = [
  "Rối loạn kinh nguyệt và nội tiết sinh sản",
  "Bệnh lý lành tính tử cung, nội mạc và cổ tử cung",
  "Nhiễm trùng và bệnh lý âm hộ - âm đạo",
  "Bệnh lý buồng trứng, phần phụ, vô sinh và sàn chậu",
  "Tổn thương tiền ung thư và ung thư phụ khoa",
  "Bệnh lý và biến chứng thai kỳ sớm",
  "Biến chứng nội khoa và bánh rau trong thai kỳ",
  "Biến chứng thai, chuyển dạ và hậu sản",
];

export const BENH_LY_SPK = [
  { stt: 1, ten: "Đau bụng kinh (thống kinh)", nhom: "Rối loạn kinh nguyệt và nội tiết sinh sản", mo_ta: "Đau vùng hạ vị liên quan đến kỳ kinh; có thể nguyên phát hoặc thứ phát do bệnh lý vùng chậu." },
  { stt: 2, ten: "Vô kinh nguyên phát", nhom: "Rối loạn kinh nguyệt và nội tiết sinh sản", mo_ta: "Không xuất hiện kinh nguyệt ở độ tuổi dự kiến, thường liên quan bất thường phát triển, nội tiết hoặc di truyền." },
  { stt: 3, ten: "Vô kinh thứ phát", nhom: "Rối loạn kinh nguyệt và nội tiết sinh sản", mo_ta: "Mất kinh ở người trước đó đã có kinh, sau khi đã loại trừ thai nghén; nguyên nhân thường do nội tiết, dinh dưỡng hoặc bệnh toàn thân." },
  { stt: 4, ten: "Chảy máu tử cung bất thường", nhom: "Rối loạn kinh nguyệt và nội tiết sinh sản", mo_ta: "Ra máu từ buồng tử cung bất thường về chu kỳ, thời gian hoặc lượng máu, không phù hợp với kinh nguyệt sinh lý." },
  { stt: 5, ten: "Cường kinh / rong kinh", nhom: "Rối loạn kinh nguyệt và nội tiết sinh sản", mo_ta: "Lượng máu kinh nhiều hoặc kéo dài, có thể gây thiếu máu và ảnh hưởng chất lượng cuộc sống." },
  { stt: 6, ten: "Kinh thưa", nhom: "Rối loạn kinh nguyệt và nội tiết sinh sản", mo_ta: "Chu kỳ kinh kéo dài hoặc số lần hành kinh ít hơn bình thường, thường phản ánh rối loạn phóng noãn." },
  { stt: 7, ten: "Hội chứng tiền kinh nguyệt (PMS)", nhom: "Rối loạn kinh nguyệt và nội tiết sinh sản", mo_ta: "Nhóm triệu chứng thể chất và cảm xúc xuất hiện trước kỳ kinh rồi giảm khi hành kinh bắt đầu." },
  { stt: 8, ten: "Rối loạn khí sắc tiền kinh nguyệt (PMDD)", nhom: "Rối loạn kinh nguyệt và nội tiết sinh sản", mo_ta: "Thể nặng của rối loạn tiền kinh nguyệt với triệu chứng tâm trạng rõ, ảnh hưởng đáng kể đến sinh hoạt." },
  { stt: 9, ten: "Hội chứng buồng trứng đa nang (PCOS)", nhom: "Rối loạn kinh nguyệt và nội tiết sinh sản", mo_ta: "Rối loạn nội tiết - chuyển hóa thường gây rối loạn phóng noãn, tăng androgen và hình ảnh buồng trứng đa nang." },
  { stt: 10, ten: "Tăng prolactin máu", nhom: "Rối loạn kinh nguyệt và nội tiết sinh sản", mo_ta: "Nồng độ prolactin cao có thể gây tiết sữa bất thường, rối loạn kinh nguyệt, giảm phóng noãn và vô sinh." },
  { stt: 11, ten: "Lạc nội mạc tử cung", nhom: "Bệnh lý lành tính tử cung, nội mạc và cổ tử cung", mo_ta: "Mô giống nội mạc tử cung phát triển ngoài buồng tử cung, thường gây đau vùng chậu và có thể liên quan vô sinh." },
  { stt: 12, ten: "Lạc nội mạc trong cơ tử cung (adenomyosis)", nhom: "Bệnh lý lành tính tử cung, nội mạc và cổ tử cung", mo_ta: "Tuyến và mô đệm nội mạc hiện diện trong cơ tử cung, thường gây đau bụng kinh, rong kinh và tử cung to." },
  { stt: 13, ten: "U xơ tử cung", nhom: "Bệnh lý lành tính tử cung, nội mạc và cổ tử cung", mo_ta: "Khối u lành tính phát sinh từ cơ trơn tử cung, có thể gây rong kinh, đau, chèn ép hoặc ảnh hưởng sinh sản." },
  { stt: 14, ten: "Polyp nội mạc tử cung", nhom: "Bệnh lý lành tính tử cung, nội mạc và cổ tử cung", mo_ta: "Tổn thương khu trú phát triển từ nội mạc tử cung, có thể gây ra máu bất thường hoặc ảnh hưởng khả năng làm tổ." },
  { stt: 15, ten: "Tăng sản nội mạc tử cung", nhom: "Bệnh lý lành tính tử cung, nội mạc và cổ tử cung", mo_ta: "Nội mạc tăng sinh quá mức, thường liên quan estrogen không đối kháng; một số thể có nguy cơ tiến triển ung thư." },
  { stt: 16, ten: "Dính buồng tử cung (hội chứng Asherman)", nhom: "Bệnh lý lành tính tử cung, nội mạc và cổ tử cung", mo_ta: "Sẹo dính trong buồng tử cung, thường xuất hiện sau can thiệp hoặc nhiễm trùng, gây giảm kinh, vô kinh hoặc vô sinh." },
  { stt: 17, ten: "Dị dạng tử cung bẩm sinh", nhom: "Bệnh lý lành tính tử cung, nội mạc và cổ tử cung", mo_ta: "Bất thường hình thái tử cung do rối loạn phát triển ống Müller, như tử cung vách, hai sừng hoặc một sừng." },
  { stt: 18, ten: "Polyp cổ tử cung", nhom: "Bệnh lý lành tính tử cung, nội mạc và cổ tử cung", mo_ta: "Tổn thương lành tính dạng cuống xuất phát từ ống cổ tử cung, có thể gây ra máu sau giao hợp hoặc giữa kỳ kinh." },
  { stt: 19, ten: "Viêm cổ tử cung", nhom: "Bệnh lý lành tính tử cung, nội mạc và cổ tử cung", mo_ta: "Tình trạng viêm tại cổ tử cung do nhiễm trùng hoặc kích thích, có thể gây khí hư, đau và chảy máu bất thường." },
  { stt: 20, ten: "Hẹp cổ tử cung", nhom: "Bệnh lý lành tính tử cung, nội mạc và cổ tử cung", mo_ta: "Ống cổ tử cung bị thu hẹp hoặc bít tắc, có thể gây ứ máu kinh, đau, vô sinh hoặc cản trở thủ thuật." },
  { stt: 21, ten: "Viêm âm đạo do vi khuẩn", nhom: "Nhiễm trùng và bệnh lý âm hộ - âm đạo", mo_ta: "Mất cân bằng hệ vi sinh âm đạo, thường gây khí hư loãng, mùi tanh và pH âm đạo tăng." },
  { stt: 22, ten: "Nhiễm nấm âm hộ - âm đạo", nhom: "Nhiễm trùng và bệnh lý âm hộ - âm đạo", mo_ta: "Nhiễm Candida gây ngứa rát, đỏ âm hộ và khí hư trắng đặc; có thể tái phát." },
  { stt: 23, ten: "Nhiễm Trichomonas", nhom: "Nhiễm trùng và bệnh lý âm hộ - âm đạo", mo_ta: "Bệnh lây truyền qua đường tình dục do ký sinh trùng, thường gây khí hư, kích ứng và viêm âm đạo." },
  { stt: 24, ten: "Nhiễm Chlamydia đường sinh dục", nhom: "Nhiễm trùng và bệnh lý âm hộ - âm đạo", mo_ta: "Nhiễm khuẩn lây truyền qua đường tình dục thường ít triệu chứng nhưng có thể gây viêm cổ tử cung và tổn thương vòi tử cung." },
  { stt: 25, ten: "Lậu đường sinh dục", nhom: "Nhiễm trùng và bệnh lý âm hộ - âm đạo", mo_ta: "Nhiễm Neisseria gonorrhoeae có thể gây viêm cổ tử cung, viêm niệu đạo và biến chứng viêm vùng chậu." },
  { stt: 26, ten: "Herpes sinh dục", nhom: "Nhiễm trùng và bệnh lý âm hộ - âm đạo", mo_ta: "Nhiễm virus herpes simplex gây mụn nước hoặc vết loét đau, có xu hướng tái phát và có thể lây cho trẻ sơ sinh." },
  { stt: 27, ten: "Nhiễm HPV sinh dục", nhom: "Nhiễm trùng và bệnh lý âm hộ - âm đạo", mo_ta: "Nhiễm papillomavirus người; một số typ gây sùi sinh dục, các typ nguy cơ cao liên quan tổn thương tiền ung thư và ung thư." },
  { stt: 28, ten: "Viêm vùng chậu (PID)", nhom: "Nhiễm trùng và bệnh lý âm hộ - âm đạo", mo_ta: "Nhiễm trùng đường sinh dục trên gồm tử cung, vòi tử cung hoặc phúc mạc chậu, có nguy cơ gây vô sinh và thai ngoài tử cung." },
  { stt: 29, ten: "Áp-xe vòi tử cung - buồng trứng", nhom: "Nhiễm trùng và bệnh lý âm hộ - âm đạo", mo_ta: "Ổ mủ phức tạp ở phần phụ, thường là biến chứng nặng của viêm vùng chậu và có thể gây nhiễm trùng huyết." },
  { stt: 30, ten: "Nang hoặc áp-xe tuyến Bartholin", nhom: "Nhiễm trùng và bệnh lý âm hộ - âm đạo", mo_ta: "Tắc ống tuyến Bartholin tạo nang; khi nhiễm trùng có thể hình thành áp-xe đau ở vùng tiền đình âm hộ." },
  { stt: 31, ten: "Nang buồng trứng cơ năng", nhom: "Bệnh lý buồng trứng, phần phụ, vô sinh và sàn chậu", mo_ta: "Nang hình thành từ hoạt động sinh lý của nang noãn hoặc hoàng thể, phần lớn lành tính và có thể tự thoái triển." },
  { stt: 32, ten: "Nang lạc nội mạc tử cung buồng trứng", nhom: "Bệnh lý buồng trứng, phần phụ, vô sinh và sàn chậu", mo_ta: "Nang chứa dịch máu cũ do lạc nội mạc tử cung tại buồng trứng, thường liên quan đau và giảm dự trữ buồng trứng." },
  { stt: 33, ten: "U quái trưởng thành buồng trứng", nhom: "Bệnh lý buồng trứng, phần phụ, vô sinh và sàn chậu", mo_ta: "Khối u tế bào mầm thường lành tính, có thể chứa nhiều loại mô và có nguy cơ gây xoắn buồng trứng." },
  { stt: 34, ten: "U nang tuyến buồng trứng lành tính", nhom: "Bệnh lý buồng trứng, phần phụ, vô sinh và sàn chậu", mo_ta: "Khối u biểu mô lành tính dạng thanh dịch hoặc nhầy, có thể đạt kích thước lớn và cần phân biệt với ác tính." },
  { stt: 35, ten: "Xoắn phần phụ / xoắn buồng trứng", nhom: "Bệnh lý buồng trứng, phần phụ, vô sinh và sàn chậu", mo_ta: "Buồng trứng và/hoặc vòi tử cung xoắn quanh cuống mạch, gây đau cấp và đe dọa mất chức năng phần phụ." },
  { stt: 36, ten: "Ứ dịch vòi tử cung", nhom: "Bệnh lý buồng trứng, phần phụ, vô sinh và sàn chậu", mo_ta: "Vòi tử cung giãn chứa dịch do tắc nghẽn, thường sau viêm nhiễm và có thể làm giảm khả năng có thai." },
  { stt: 37, ten: "Vô sinh nữ", nhom: "Bệnh lý buồng trứng, phần phụ, vô sinh và sàn chậu", mo_ta: "Không đạt thai sau một khoảng thời gian quan hệ đều đặn không tránh thai; nguyên nhân có thể do phóng noãn, vòi tử cung, tử cung hoặc tuổi." },
  { stt: 38, ten: "Suy giảm dự trữ buồng trứng", nhom: "Bệnh lý buồng trứng, phần phụ, vô sinh và sàn chậu", mo_ta: "Số lượng hoặc chất lượng noãn còn lại thấp hơn dự kiến theo tuổi, ảnh hưởng khả năng sinh sản và đáp ứng kích thích buồng trứng." },
  { stt: 39, ten: "Sa cơ quan vùng chậu", nhom: "Bệnh lý buồng trứng, phần phụ, vô sinh và sàn chậu", mo_ta: "Tử cung, bàng quang, trực tràng hoặc đỉnh âm đạo sa xuống do suy yếu hệ thống nâng đỡ sàn chậu." },
  { stt: 40, ten: "Tiểu không tự chủ khi gắng sức", nhom: "Bệnh lý buồng trứng, phần phụ, vô sinh và sàn chậu", mo_ta: "Rò tiểu khi ho, hắt hơi, cười hoặc vận động do suy yếu cơ thắt niệu đạo và cấu trúc nâng đỡ." },
  { stt: 41, ten: "Tân sinh trong biểu mô cổ tử cung (CIN)", nhom: "Tổn thương tiền ung thư và ung thư phụ khoa", mo_ta: "Biến đổi tiền ung thư của tế bào cổ tử cung, thường liên quan HPV nguy cơ cao và được phân độ theo mức độ tổn thương." },
  { stt: 42, ten: "Ung thư cổ tử cung", nhom: "Tổn thương tiền ung thư và ung thư phụ khoa", mo_ta: "Ung thư phát sinh tại cổ tử cung, phần lớn liên quan nhiễm HPV nguy cơ cao kéo dài." },
  { stt: 43, ten: "Ung thư nội mạc tử cung", nhom: "Tổn thương tiền ung thư và ung thư phụ khoa", mo_ta: "Ung thư xuất phát từ lớp nội mạc tử cung, thường biểu hiện bằng ra máu tử cung bất thường, đặc biệt sau mãn kinh." },
  { stt: 44, ten: "Ung thư buồng trứng", nhom: "Tổn thương tiền ung thư và ung thư phụ khoa", mo_ta: "Nhóm ung thư phát sinh từ biểu mô, tế bào mầm hoặc mô đệm buồng trứng; thường được phát hiện muộn do triệu chứng không đặc hiệu." },
  { stt: 45, ten: "Ung thư vòi tử cung", nhom: "Tổn thương tiền ung thư và ung thư phụ khoa", mo_ta: "Ung thư hiếm xuất phát từ vòi tử cung; nhiều trường hợp thuộc phổ ung thư thanh dịch độ cao của vòi - buồng trứng - phúc mạc." },
  { stt: 46, ten: "Ung thư phúc mạc nguyên phát", nhom: "Tổn thương tiền ung thư và ung thư phụ khoa", mo_ta: "Ung thư ác tính của phúc mạc có đặc điểm tương tự ung thư biểu mô buồng trứng dù buồng trứng có thể không phải vị trí khởi phát." },
  { stt: 47, ten: "Ung thư âm hộ", nhom: "Tổn thương tiền ung thư và ung thư phụ khoa", mo_ta: "Ung thư phát sinh tại da hoặc niêm mạc âm hộ, có thể liên quan HPV hoặc bệnh lý viêm mạn tính." },
  { stt: 48, ten: "Ung thư âm đạo", nhom: "Tổn thương tiền ung thư và ung thư phụ khoa", mo_ta: "Ung thư hiếm của âm đạo, thường là ung thư biểu mô tế bào vảy và có thể liên quan HPV." },
  { stt: 49, ten: "Sarcoma tử cung", nhom: "Tổn thương tiền ung thư và ung thư phụ khoa", mo_ta: "Nhóm ung thư hiếm phát sinh từ cơ tử cung hoặc mô liên kết, gồm leiomyosarcoma và sarcoma mô đệm nội mạc." },
  { stt: 50, ten: "Tân sinh nguyên bào nuôi thai kỳ", nhom: "Tổn thương tiền ung thư và ung thư phụ khoa", mo_ta: "Nhóm bệnh ác tính từ mô nguyên bào nuôi sau thai trứng hoặc thai kỳ khác, thường theo dõi bằng beta-hCG." },
  { stt: 51, ten: "Thai ngoài tử cung", nhom: "Bệnh lý và biến chứng thai kỳ sớm", mo_ta: "Trứng đã thụ tinh làm tổ ngoài buồng tử cung, thường ở vòi tử cung; có nguy cơ vỡ và xuất huyết trong ổ bụng." },
  { stt: 52, ten: "Dọa sảy thai", nhom: "Bệnh lý và biến chứng thai kỳ sớm", mo_ta: "Ra máu âm đạo trước tuổi thai có khả năng sống trong khi cổ tử cung còn đóng và thai vẫn có dấu hiệu sống." },
  { stt: 53, ten: "Sảy thai tự nhiên", nhom: "Bệnh lý và biến chứng thai kỳ sớm", mo_ta: "Thai kỳ kết thúc tự nhiên trước ngưỡng thai có khả năng sống theo quy định chuyên môn từng quốc gia." },
  { stt: 54, ten: "Thai lưu sớm / sảy thai lưu", nhom: "Bệnh lý và biến chứng thai kỳ sớm", mo_ta: "Phôi hoặc thai đã ngừng phát triển nhưng chưa được tống xuất khỏi buồng tử cung." },
  { stt: 55, ten: "Sảy thai không hoàn toàn", nhom: "Bệnh lý và biến chứng thai kỳ sớm", mo_ta: "Một phần sản phẩm thụ thai đã được tống ra nhưng vẫn còn mô trong buồng tử cung, thường gây chảy máu kéo dài." },
  { stt: 56, ten: "Sảy thai liên tiếp", nhom: "Bệnh lý và biến chứng thai kỳ sớm", mo_ta: "Mất thai tự nhiên lặp lại từ hai lần trở lên; cần đánh giá nguyên nhân giải phẫu, di truyền, nội tiết, miễn dịch và các yếu tố khác." },
  { stt: 57, ten: "Thai trứng", nhom: "Bệnh lý và biến chứng thai kỳ sớm", mo_ta: "Tăng sinh bất thường của nguyên bào nuôi với phù gai rau, gồm thai trứng toàn phần và bán phần." },
  { stt: 58, ten: "Nôn nghén nặng", nhom: "Bệnh lý và biến chứng thai kỳ sớm", mo_ta: "Buồn nôn và nôn mức độ nặng trong thai kỳ gây mất nước, rối loạn điện giải, giảm cân hoặc suy dinh dưỡng." },
  { stt: 59, ten: "Hở eo tử cung", nhom: "Bệnh lý và biến chứng thai kỳ sớm", mo_ta: "Cổ tử cung mở hoặc ngắn không đau ở tam cá nguyệt hai, làm tăng nguy cơ sảy thai muộn hoặc sinh non." },
  { stt: 60, ten: "Sảy thai nhiễm khuẩn", nhom: "Bệnh lý và biến chứng thai kỳ sớm", mo_ta: "Nhiễm trùng tử cung liên quan sảy thai hoặc can thiệp thai kỳ, có thể tiến triển nhanh thành nhiễm trùng huyết." },
  { stt: 61, ten: "Tăng huyết áp thai kỳ", nhom: "Biến chứng nội khoa và bánh rau trong thai kỳ", mo_ta: "Tăng huyết áp xuất hiện sau 20 tuần thai mà chưa có dấu hiệu tiền sản giật tại thời điểm chẩn đoán." },
  { stt: 62, ten: "Tiền sản giật", nhom: "Biến chứng nội khoa và bánh rau trong thai kỳ", mo_ta: "Rối loạn tăng huyết áp thai kỳ kèm tổn thương cơ quan hoặc rối loạn chức năng bánh rau, có thể đe dọa mẹ và thai." },
  { stt: 63, ten: "Sản giật", nhom: "Biến chứng nội khoa và bánh rau trong thai kỳ", mo_ta: "Cơn co giật mới xuất hiện ở người bệnh tiền sản giật mà không giải thích được bằng nguyên nhân thần kinh khác." },
  { stt: 64, ten: "Hội chứng HELLP", nhom: "Biến chứng nội khoa và bánh rau trong thai kỳ", mo_ta: "Biến chứng nặng với tan máu, tăng men gan và giảm tiểu cầu, thường nằm trong phổ tiền sản giật." },
  { stt: 65, ten: "Đái tháo đường thai kỳ", nhom: "Biến chứng nội khoa và bánh rau trong thai kỳ", mo_ta: "Rối loạn dung nạp glucose được phát hiện lần đầu trong thai kỳ, làm tăng nguy cơ biến chứng cho mẹ và thai." },
  { stt: 66, ten: "Rau tiền đạo", nhom: "Biến chứng nội khoa và bánh rau trong thai kỳ", mo_ta: "Bánh rau bám thấp và che một phần hoặc toàn bộ lỗ trong cổ tử cung, thường gây chảy máu không đau cuối thai kỳ." },
  { stt: 67, ten: "Phổ rau cài răng lược", nhom: "Biến chứng nội khoa và bánh rau trong thai kỳ", mo_ta: "Bánh rau bám hoặc xâm lấn bất thường vào cơ tử cung, làm tăng nguy cơ xuất huyết nặng khi sinh." },
  { stt: 68, ten: "Rau bong non", nhom: "Biến chứng nội khoa và bánh rau trong thai kỳ", mo_ta: "Bánh rau tách khỏi thành tử cung trước khi thai được sinh, có thể gây đau, chảy máu và suy thai cấp." },
  { stt: 69, ten: "Vỡ ối non trước chuyển dạ", nhom: "Biến chứng nội khoa và bánh rau trong thai kỳ", mo_ta: "Màng ối vỡ trước khi chuyển dạ bắt đầu; nếu xảy ra trước 37 tuần gọi là vỡ ối non trước chuyển dạ ở thai non tháng." },
  { stt: 70, ten: "Chuyển dạ sinh non", nhom: "Biến chứng nội khoa và bánh rau trong thai kỳ", mo_ta: "Cơn co tử cung đều gây thay đổi cổ tử cung trước 37 tuần thai, có nguy cơ dẫn đến sinh non." },
  { stt: 71, ten: "Thai chậm tăng trưởng trong tử cung", nhom: "Biến chứng thai, chuyển dạ và hậu sản", mo_ta: "Thai không đạt tiềm năng tăng trưởng, thường liên quan suy chức năng bánh rau và tăng nguy cơ bệnh tật chu sinh." },
  { stt: 72, ten: "Thiểu ối", nhom: "Biến chứng thai, chuyển dạ và hậu sản", mo_ta: "Thể tích nước ối thấp hơn dự kiến theo tuổi thai, có thể liên quan vỡ ối, bất thường thai hoặc suy bánh rau." },
  { stt: 73, ten: "Đa ối", nhom: "Biến chứng thai, chuyển dạ và hậu sản", mo_ta: "Thể tích nước ối tăng quá mức, có thể liên quan đái tháo đường, bất thường thai hoặc không rõ nguyên nhân." },
  { stt: 74, ten: "Ứ mật trong gan thai kỳ", nhom: "Biến chứng thai, chuyển dạ và hậu sản", mo_ta: "Bệnh gan đặc hiệu của thai kỳ gây ngứa và tăng acid mật, liên quan nguy cơ biến cố bất lợi cho thai." },
  { stt: 75, ten: "Nhiễm trùng ối / viêm màng ối", nhom: "Biến chứng thai, chuyển dạ và hậu sản", mo_ta: "Nhiễm trùng trong buồng ối, màng ối, bánh rau hoặc nước ối, thường liên quan vỡ ối kéo dài và sốt mẹ." },
  { stt: 76, ten: "Sa dây rốn", nhom: "Biến chứng thai, chuyển dạ và hậu sản", mo_ta: "Dây rốn nằm dưới hoặc sa qua phần trình diện sau vỡ ối, có nguy cơ bị chèn ép gây thiếu oxy thai cấp." },
  { stt: 77, ten: "Kẹt vai", nhom: "Biến chứng thai, chuyển dạ và hậu sản", mo_ta: "Sau khi đầu thai đã sổ, vai trước bị mắc sau khớp vệ, cần xử trí cấp cứu bằng các thủ thuật sản khoa." },
  { stt: 78, ten: "Vỡ tử cung", nhom: "Biến chứng thai, chuyển dạ và hậu sản", mo_ta: "Rách toàn bộ hoặc một phần thành tử cung trong thai kỳ hoặc chuyển dạ, thường gây xuất huyết và suy thai nghiêm trọng." },
  { stt: 79, ten: "Băng huyết sau sinh", nhom: "Biến chứng thai, chuyển dạ và hậu sản", mo_ta: "Mất máu quá mức sau sinh do đờ tử cung, chấn thương đường sinh dục, sót rau hoặc rối loạn đông máu." },
  { stt: 80, ten: "Viêm nội mạc tử cung hậu sản", nhom: "Biến chứng thai, chuyển dạ và hậu sản", mo_ta: "Nhiễm trùng lớp nội mạc tử cung sau sinh, thường biểu hiện sốt, đau tử cung và sản dịch bất thường." },
];
